apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cert-manager-external-secret
  namespace: network
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cert-manager-secret
  data:
  - secretKey: apiToken
    remoteRef:
      key: /network/certmanager
      property: apiToken
