apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-test
  namespace: network
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: ${INFRA_LETS_ENCRYPT_EMAIL}
    privateKeySecretRef:
      name: letsencrypt-test
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cert-manager-secret
            key: apiToken
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: network
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ${INFRA_LETS_ENCRYPT_EMAIL}
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cert-manager-secret
            key: apiToken
