#!/bin/bash

set -eu

# Add helm repository
helm repo add hashicorp https://helm.releases.hashicorp.com
helm repo update

kubectl create namespace vault || true

# vault
echo -e "\nDeploying vault..."
vault_dir="$(dirname $0)/../vault"

# Replace secrets
sed -i "s|<path:secret/data/infra#domain>|${DOMAIN}|" "${vault_dir}"/values.yaml

kubectl kustomize "${vault_dir}" --enable-helm | kubectl apply -f -
