apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: alloy-route
  namespace: monitoring
spec:
  parentRefs:
  - name: cluster-gateway
    namespace: network
    sectionName: https
  hostnames:
  - "alloy.${INFRA_DOMAIN}"
  rules:
  - backendRefs:
    - name: alloy
      port: 12345
