apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: test-secret
  namespace: default
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-secretstore
    kind: ClusterSecretStore
  target:
    template:
      engineVersion: v2
      data:
        sensitive_values.yaml: |
          global:
            domain: cd."{{ .domain }}"

          configs:
            credentialTemplates:
              home-kops-credentials:
                password: "{{ .gh_org_password }}"
                username: "{{ .gh_org_username }}"
            secret:
              createSecret: true
              argocdServerAdminPassword: "{{ .admin_password }}"<path:secret/data/devopstools/argocd#admin_password>
              argocdServerAdminPasswordMtime: "2025-06-15T12:00:00Z"
  data:
  - secretKey: domain
    remoteRef:
      key: /infra
  - secretKey: admin_password
    remoteRef:
      key: /devopstools/argocd
      property: admin_password
  - secretKey: gh_org_password
    remoteRef:
      key: /devopstools/argocd
      property: gh_org1_password
  - secretKey: gh_org_username
    remoteRef:
      key: /devopstools/argocd
      property: gh_org1_username
