---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-vault-plugin-credentials
  namespace: devops-tools
type: Opaque
stringData:
  AVP_AUTH_TYPE: k8s
  AVP_K8S_ROLE: argocd-reader
  AVP_TYPE: vault
  VAULT_ADDR: http://vault.vault:8200
