#!/bin/bash

set -eu

project_path="$(dirname $0)/.."

# Install nfs storage class
nfs_dir="${project_path}/nfs-sc"

sed -i "s|<path:secret/data/infra#k8s_nfs>|${K8S_NFS}|" "${nfs_dir}"/values.yaml

helm upgrade nfs-sc "${nfs_dir}" \
  --install \
  --namespace default \
  --values "${nfs_dir}"/values.yaml \
  --wait
