#!/bin/bash

project_dir="$1"

# Install nfs storage class
nfs_dir="${project_dir}/default/nfs-sc"

sed -i "s|<path:secret/data/infra#k8s_nfs>|${K8S_NFS}|" "${nfs_dir}"/values.yaml

helm upgrade nfs-sc "${nfs_dir}" \
  --install \
  --namespace default \
  --file "${nfs_dir}"/values.yaml \
  --wait

# Install sealed secrets
certificates_dir="${project_dir}/default/sealed-secrets/certificates"

kubectl create secret tls sealed-secrets-key \
  --cert="${certificates_dir}/cert.pem" \
  --key="${certificates_dir}/key.pem" \
  --namespace default \
  --dry-run=client -o yaml | kubectl apply -f -

helm upgrade sealed-secrets sealed-secrets/sealed-secrets \
  --install \
  --namespace default \
  --values "${project_dir}/default/sealed-secrets/values.yaml" \
  --wait

# Install replicator
helm upgrade kubernetes-replicator mittwald/kubernetes-replicator \
  --install \
  --namespace default \
  --values "${project_dir}/default/replicator/values.yaml" \
  --wait
