#!/bin/bash

# Verify requirements
verify_requirements() {
  local project_dir=""
  project_dir="$1"

  if ! which kubectl 2>&1 > /dev/null; then
    echo "    [!] kubect not detected!"
    error="1"
  fi

  if ! which helm 2>&1 > /dev/null; then
    echo "    [!] helm not detected!"
    error="1"
  fi

  if [[ $error ]]; then
    exit 1
  fi
}

project_dir="$(git rev-parse --show-toplevel)"

echo "[+] Verifying requirements..."
verify_requirements "${project_dir}"
echo -e "    Everything ready!\\n"

# Install gateway crds
kubectl apply --server-side -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.4.0/experimental-install.yaml

echo "[1/5] Bootstraping cni..."
"${project_dir}"/kube-system/tooling/bootstrap
echo -e "   CNI ready!\\n"

echo "[2/5] Bootstraping network..."
"${project_dir}"/network/tooling/bootstrap
echo -e "   Network ready!\\n"

echo "[3/5] Bootstraping core services..."
"${project_dir}"/default/tooling/bootstrap
echo -e "   Core services ready!\\n"

echo "[4/5] Bootstraping vault..."
"${project_dir}"/vault/tooling/bootstrap
echo -e "   Vault ready!\\n"

echo "[5/5] Bootstraping devops-tools..."
"${project_dir}"/devops-tools/tooling/bootstrap
echo -e "   Devops-tools ready!\\n"

echo "[+] Cluster services ready!"
