#!/bin/bash

if [[ -z "${ENV}" ]]; then
  ENV="test"
fi

set -a && source .env.${ENV} && set +a

# Verify requirements
verify_requirements() {
  local project_dir=""
  project_dir="$1"

  if ! which kubectl 2>&1 > /dev/null; then
    echo "    [!] kubect not detected!"
    error="1"
  fi

  if ! which helm 2>&1 > /dev/null; then
    echo "    [!] helm not detected!"
    error="1"
  fi

  if [[ $error ]]; then
    exit 1
  fi
}

project_dir="$(git rev-parse --show-toplevel)"

echo "[+] Verifying requirements..."
verify_requirements "${project_dir}"
echo -e "    Everything ready!\\n"

# Install gateway crds
kubectl apply --server-side -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.4.0/experimental-install.yaml

echo "[1/4] Bootstraping network..."
"${project_dir}"/network/tooling/bootstrap
echo -e "   Network ready!\\n"

exit 0

echo "[2/4] Bootstraping core services..."
"${project_dir}"/default/tooling/bootstrap
echo -e "   Core services ready!\\n"

echo "[3/4] Bootstraping vault..."
"${project_dir}"/vault/tooling/bootstrap
echo -e "   Vault ready!\\n"

echo "[4/4] Bootstraping devops-tools..."
"${project_dir}"/devops-tools/tooling/bootstrap
echo -e "   Devops-tools ready!\\n"

echo "[+] Cluster services ready!"
